/**
 * Utility helper to handle downloading/exporting analyzed data into
 * Markdown (.md), DOCX (.doc), and PDF (.pdf).
 */

/**
 * Compile document analysis into markdown text
 */
function compileMarkdown(doc) {
  const { fileName, category, analysis, detectiveReport, highlights } = doc;
  
  let md = `# AI Forensic Report: ${fileName}\n`;
  md += `*Generated by AuraDoc Multimodal Document Portal*\n\n`;
  
  md += `## Document Metadata\n`;
  md += `- **File Name**: ${fileName}\n`;
  md += `- **Detected Category**: ${category?.toUpperCase()}\n`;
  md += `- **Primary Language**: ${analysis?.language || 'English'}\n\n`;
  
  md += `## AI Executive Summary\n`;
  md += `${analysis?.summary || 'No summary compiled.'}\n\n`;
  
  // Category specific fields
  if (category === 'resume') {
    md += `## Resume Strength Audit\n`;
    md += `- **ATS Score Score**: ${analysis?.atsScore || 0}/100\n\n`;
    md += `### Candidate Strengths\n`;
    analysis?.strengths?.forEach(s => { md += `- ${s}\n`; });
    md += `\n### Missing Competencies / Keywords\n`;
    analysis?.missingSkills?.forEach(m => { md += `- ${m}\n`; });
    md += `\n`;
  } else if (category === 'invoice') {
    md += `## Billing & Invoice Metadata\n`;
    md += `- **Company / Vendor**: ${analysis?.company || 'Not specified'}\n`;
    md += `- **Invoice Date**: ${analysis?.date || 'Not specified'}\n`;
    md += `- **Total Amount**: ${analysis?.currency || 'INR'} ${analysis?.amount || 0}\n`;
    md += `- **GSTIN / Tax ID**: ${analysis?.gst || 'Not found'}\n\n`;
    
    md += `### Billed Line Items\n`;
    md += `| # | Item Description | Amount |\n`;
    md += `|---|------------------|--------|\n`;
    analysis?.lineItems?.forEach((item, idx) => {
      md += `| ${idx+1} | ${item.description} | ${analysis?.currency || 'INR'} ${item.amount} |\n`;
    });
    md += `\n`;
  } else if (category === 'medical') {
    md += `## Clinical Diagnosis Findings\n`;
    md += `### Vital Readings\n`;
    if (analysis?.vitalSigns) {
      Object.entries(analysis.vitalSigns).forEach(([k, v]) => {
        md += `- **${k}**: ${v}\n`;
      });
    }
    
    md += `\n### Diagnostic Summaries\n`;
    analysis?.findings?.forEach(f => { md += `- ${f}\n`; });
    md += `\n### Clinical Recommendations\n`;
    analysis?.recommendations?.forEach(r => { md += `- ${r}\n`; });
    md += `\n### Flags & Abnormalities\n`;
    analysis?.abnormalities?.forEach(a => { md += `- [CRITICAL] ${a}\n`; });
    md += `\n`;
  } else if (category === 'paper') {
    md += `## Research Paper Summary\n`;
    md += `### Abstract\n${analysis?.abstract || ''}\n\n`;
    md += `### Scientific Methodology\n${analysis?.methodology || ''}\n\n`;
    md += `### Core Contributions / Findings\n`;
    analysis?.keyFindings?.forEach(k => { md += `- ${k}\n`; });
    md += `\n### Conclusions & Avenues\n${analysis?.conclusions || ''}\n\n`;
  }
  
  md += `## Smart Highlights Detected\n`;
  highlights?.forEach((h, idx) => {
    md += `### Highlight #${idx + 1} (${h.type.toUpperCase()})\n`;
    md += `*Snippet*: "${h.text}"\n`;
    md += `*AI Context*: ${h.explanation}\n\n`;
  });
  
  md += `## AI Document Detective Audit\n`;
  md += `- **Suspicion Meter**: ${detectiveReport?.score || 0}% (${detectiveReport?.status?.toUpperCase()})\n\n`;
  md += `### Audit Ledger\n`;
  detectiveReport?.findings?.forEach(f => {
    md += `- [${f.severity.toUpperCase()}] **${f.indicator}**: ${f.details}\n`;
  });
  md += `\n`;

  return md;
}

/**
 * Downloads a text string as a file
 */
function downloadFile(content, fileName, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Exports analyzed document as Markdown
 */
export function exportToMarkdown(doc) {
  const mdContent = compileMarkdown(doc);
  const cleanName = doc.fileName.split('.')[0].replace(/\s+/g, '_');
  downloadFile(mdContent, `${cleanName}_Forensic_Report.md`, 'text/markdown;charset=utf-8;');
}

/**
 * Exports analyzed document as DOCX (MS Word compatible XML/HTML wrapper)
 */
export function exportToDocx(doc) {
  const mdContent = compileMarkdown(doc);
  
  // Format as highly legible HTML with basic styling that MS Word translates perfectly
  const htmlContent = `
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head>
      <title>AI Document Forensic Report</title>
      <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; color: #333; line-height: 1.5; padding: 20px; }
        h1 { color: #8b5cf6; font-size: 24px; border-bottom: 2px solid #8b5cf6; padding-bottom: 8px; }
        h2 { color: #06b6d4; font-size: 18px; margin-top: 20px; border-bottom: 1px dashed #ddd; padding-bottom: 4px; }
        h3 { font-size: 14px; margin-top: 15px; color: #444; }
        ul { padding-left: 20px; }
        li { margin-bottom: 6px; }
        table { border-collapse: collapse; width: 100%; margin-top: 10px; }
        th, td { border: 1px solid #ddd; padding: 8px; font-size: 13px; text-align: left; }
        th { background-color: #f3f4f6; font-weight: bold; }
        .highlight { background-color: #fef08a; padding: 2px 4px; border-radius: 4px; font-style: italic; }
      </style>
    </head>
    <body>
      ${mdContent
        .replace(/# (.*)\n/g, '<h1>$1</h1>')
        .replace(/## (.*)\n/g, '<h2>$1</h2>')
        .replace(/### (.*)\n/g, '<h3>$1</h3>')
        .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
        .replace(/\*([^*]+)\*/g, '<span class="highlight">$1</span>')
        .replace(/\n\n/g, '<br/>')
        .replace(/- (.*)\n/g, '<li>$1</li>')
      }
    </body>
    </html>
  `;
  
  const cleanName = doc.fileName.split('.')[0].replace(/\s+/g, '_');
  downloadFile(htmlContent, `${cleanName}_Forensic_Report.doc`, 'application/msword;charset=utf-8;');
}

/**
 * Triggers document printing mode for clean PDF formatting
 */
export function exportToPdf() {
  window.print();
}
